version: '3'
networks:
  bymn:
    external:
      name: nginx_alfa
services:
    nginx_server:
        container_name: nginx_alf
        image: pruebafifo
        ports:
            - 8083:8083
        restart: always
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
              constraints:
                - node.hostname == blocksaas-01
